// 관리 중인 전체 사이트의 통계 및 SEO 지표 메타데이터
// 데이터 출처: OpenSEO Hub (GSC, GA4, DataForSEO, 네이버 검색광고 API, Cloudflare)

export const PERIODS = [
  { id: "7d", label: "최근 7일", shortLabel: "7일", days: 7 },
  { id: "28d", label: "최근 28일", shortLabel: "28일", days: 28, isDefault: true },
  { id: "90d", label: "최근 90일", shortLabel: "90일", days: 90 },
];

export const SITES_METRICS = [
  {
    id: "everydaytutor",
    name: "EverydayTutor",
    shortName: "EverydayTutor",
    domain: "everydaytutor.net",
    url: "https://www.everydaytutor.net",
    category: "과외 매칭 플랫폼 / 글로벌 에듀테크",
    badge: "글로벌 에듀",
    icon: "🎓",
    accentColor: "#3b82f6",
    stack: "Next.js 14 · Cloudflare Pages · Vercel DNS",
    integrations: {
      gsc: { connected: true, property: "sc-domain:everydaytutor.net", account: "garmgoondev@gmail.com" },
      ga4: { connected: true, property: "properties/554632841", stream: "EverydayTutor Web (향상된 측정 ON)" },
      cloudflare: { connected: true, type: "Pages + Email Routing" },
      audit: { status: "완료", issues: 17 },
    },
    overview: {
      clicks28d: 1,
      impressions28d: 67,
      ctr: 1.5,
      avgPosition: 16.7,
      users28d: 18,
      sessions28d: 24,
      engagementRate: 100,
      avgDuration: "2분 14초",
      indexedPages: 24,
      conversions: { label: "튜터 문의 및 매칭 클릭", count: 3, unit: "건" },
      periods: {
        "7d": {
          clicks: 1,
          impressions: 22,
          ctr: 4.5,
          avgPosition: 15.8,
          users: 6,
          sessions: 8,
          engagementRate: 100,
          avgDuration: "2분 30초",
          conversions: 1,
        },
        "28d": {
          clicks: 1,
          impressions: 67,
          ctr: 1.5,
          avgPosition: 16.7,
          users: 18,
          sessions: 24,
          engagementRate: 100,
          avgDuration: "2분 14초",
          conversions: 3,
        },
        "90d": {
          clicks: 3,
          impressions: 185,
          ctr: 1.6,
          avgPosition: 17.5,
          users: 48,
          sessions: 68,
          engagementRate: 98,
          avgDuration: "2분 08초",
          conversions: 7,
        },
      },
    },
    history: {
      "7d": [
        { date: "10/02", impressions: 8, clicks: 0, users: 2 },
        { date: "10/03", impressions: 12, clicks: 0, users: 3 },
        { date: "10/04", impressions: 10, clicks: 1, users: 4 },
        { date: "10/05", impressions: 15, clicks: 0, users: 3 },
        { date: "10/06", impressions: 9, clicks: 0, users: 2 },
        { date: "10/07", impressions: 11, clicks: 0, users: 4 },
        { date: "10/08", impressions: 14, clicks: 0, users: 3 },
      ],
      "28d": [
        { date: "09/10", impressions: 9, clicks: 0, users: 2 },
        { date: "09/14", impressions: 14, clicks: 0, users: 3 },
        { date: "09/18", impressions: 11, clicks: 0, users: 3 },
        { date: "09/22", impressions: 18, clicks: 0, users: 4 },
        { date: "09/26", impressions: 12, clicks: 0, users: 2 },
        { date: "09/30", impressions: 16, clicks: 0, users: 3 },
        { date: "10/04", impressions: 10, clicks: 1, users: 4 },
        { date: "10/08", impressions: 14, clicks: 0, users: 3 },
      ],
      "90d": [
        { date: "07/15", impressions: 18, clicks: 0, users: 5 },
        { date: "07/30", impressions: 24, clicks: 0, users: 6 },
        { date: "08/15", impressions: 28, clicks: 1, users: 9 },
        { date: "08/30", impressions: 32, clicks: 0, users: 8 },
        { date: "09/15", impressions: 38, clicks: 1, users: 12 },
        { date: "09/30", impressions: 42, clicks: 1, users: 11 },
        { date: "10/08", impressions: 45, clicks: 0, users: 12 },
      ],
    },
    history7d: [
      { date: "10/02", impressions: 8, clicks: 0, users: 2 },
      { date: "10/03", impressions: 12, clicks: 0, users: 3 },
      { date: "10/04", impressions: 10, clicks: 1, users: 4 },
      { date: "10/05", impressions: 15, clicks: 0, users: 3 },
      { date: "10/06", impressions: 9, clicks: 0, users: 2 },
      { date: "10/07", impressions: 11, clicks: 0, users: 4 },
      { date: "10/08", impressions: 14, clicks: 0, users: 3 },
    ],
    topQueries: [
      { query: "高中英文家教行情", rank: 25.3, clicks: 1, impressions: 12, ctr: 8.3, status: "1페이지 유력 🔥" },
      { query: "台北家教行情", rank: 18.2, clicks: 0, impressions: 22, ctr: 0.0, status: "2페이지 상위" },
      { query: "國中英文家教時薪", rank: 24.1, clicks: 0, impressions: 15, ctr: 0.0, status: "2페이지 중위" },
      { query: "대만 영어 과외 시세", rank: 14.5, clicks: 0, impressions: 9, ctr: 0.0, status: "10위권 진입" },
      { query: "taiwan english tutor rates", rank: 21.0, clicks: 0, impressions: 9, ctr: 0.0, status: "타깃 키워드" },
    ],
    topPages: [
      { path: "/insights/taipei-english-tutor-rates", title: "대만 타이베이 영어 과외 시세 인사이트", views: 42, clicks: 1 },
      { path: "/tutors", title: "튜터 검색 및 필터", views: 28, clicks: 0 },
      { path: "/", title: "홈페이지 메인", views: 18, clicks: 0 },
    ],
    actionItems: [
      "현재 17~25위권에 위치한 '高中英文家教行情'(고교 영어 과외 시세) 검색어의 1페이지(5위 이내) 진입을 위한 메타 타이틀/디스크립션 리라이팅 가이드 적용",
      "대만(zh-TW) 학부모 검색 의도 반영한 FAQ 구조화 데이터(Schema.org) 마크업 추가",
      "과외 매칭 신청 전환(CTA) 버튼 가시성 강화 및 GA4 맞춤 이벤트 추적",
    ],
    targetMarket: "대만(zh-TW) 및 글로벌(en)",
  },
  {
    id: "pwstudio",
    name: "PW Studio",
    shortName: "PW Studio",
    domain: "pwstudio.kr",
    url: "https://pwstudio.kr",
    category: "웹 개발 / 디지털 솔루션 스튜디오",
    badge: "개발 스튜디오",
    icon: "💻",
    accentColor: "#8b5cf6",
    stack: "Next.js App Router · Cloudflare Pages · Turbopack",
    integrations: {
      gsc: { connected: true, property: "sc-domain:pwstudio.kr", account: "garmgoondev@gmail.com" },
      ga4: { connected: true, property: "properties/557301461", stream: "PW Studio (G-B2EWMRBHTN)" },
      cloudflare: { connected: true, type: "Pages Custom Domain + DNS" },
      audit: { status: "완료 (이슈 95.8% 감소)", issues: 1 },
    },
    overview: {
      clicks28d: 0,
      impressions28d: 12,
      ctr: 0.0,
      avgPosition: 32.4,
      users28d: 8,
      sessions28d: 12,
      engagementRate: 87.5,
      avgDuration: "1분 40초",
      indexedPages: 8,
      conversions: { label: "제작 문의 폼 진입", count: 5, unit: "건" },
      periods: {
        "7d": {
          clicks: 0,
          impressions: 5,
          ctr: 0.0,
          avgPosition: 30.1,
          users: 3,
          sessions: 4,
          engagementRate: 85.0,
          avgDuration: "1분 30초",
          conversions: 2,
        },
        "28d": {
          clicks: 0,
          impressions: 12,
          ctr: 0.0,
          avgPosition: 32.4,
          users: 8,
          sessions: 12,
          engagementRate: 87.5,
          avgDuration: "1분 40초",
          conversions: 5,
        },
        "90d": {
          clicks: 1,
          impressions: 28,
          ctr: 3.6,
          avgPosition: 34.0,
          users: 19,
          sessions: 28,
          engagementRate: 88.0,
          avgDuration: "1분 45초",
          conversions: 11,
        },
      },
    },
    history: {
      "7d": [
        { date: "10/02", impressions: 1, clicks: 0, users: 1 },
        { date: "10/03", impressions: 2, clicks: 0, users: 2 },
        { date: "10/04", impressions: 1, clicks: 0, users: 1 },
        { date: "10/05", impressions: 3, clicks: 0, users: 1 },
        { date: "10/06", impressions: 2, clicks: 0, users: 2 },
        { date: "10/07", impressions: 2, clicks: 0, users: 1 },
        { date: "10/08", impressions: 3, clicks: 0, users: 2 },
      ],
      "28d": [
        { date: "09/10", impressions: 1, clicks: 0, users: 1 },
        { date: "09/14", impressions: 2, clicks: 0, users: 1 },
        { date: "09/18", impressions: 1, clicks: 0, users: 1 },
        { date: "09/22", impressions: 3, clicks: 0, users: 2 },
        { date: "09/26", impressions: 2, clicks: 0, users: 1 },
        { date: "09/30", impressions: 2, clicks: 0, users: 1 },
        { date: "10/04", impressions: 1, clicks: 0, users: 1 },
        { date: "10/08", impressions: 3, clicks: 0, users: 2 },
      ],
      "90d": [
        { date: "07/15", impressions: 2, clicks: 0, users: 2 },
        { date: "07/30", impressions: 3, clicks: 0, users: 3 },
        { date: "08/15", impressions: 4, clicks: 1, users: 4 },
        { date: "08/30", impressions: 5, clicks: 0, users: 3 },
        { date: "09/15", impressions: 6, clicks: 0, users: 4 },
        { date: "09/30", impressions: 6, clicks: 0, users: 3 },
        { date: "10/08", impressions: 7, clicks: 0, users: 5 },
      ],
    },
    history7d: [
      { date: "10/02", impressions: 1, clicks: 0, users: 1 },
      { date: "10/03", impressions: 2, clicks: 0, users: 2 },
      { date: "10/04", impressions: 1, clicks: 0, users: 1 },
      { date: "10/05", impressions: 3, clicks: 0, users: 1 },
      { date: "10/06", impressions: 2, clicks: 0, users: 2 },
      { date: "10/07", impressions: 2, clicks: 0, users: 1 },
      { date: "10/08", impressions: 3, clicks: 0, users: 2 },
    ],
    topQueries: [
      { query: "PW Studio 개발", rank: 8.2, clicks: 0, impressions: 3, ctr: 0.0, status: "브랜드 키워드 1페이지" },
      { query: "소상공인 웹사이트 제작", rank: 28.4, clicks: 0, impressions: 5, ctr: 0.0, status: "공략 키워드" },
      { query: "반응형 웹 구축 스튜디오", rank: 34.1, clicks: 0, impressions: 4, ctr: 0.0, status: "신규 등록" },
    ],
    topPages: [
      { path: "/", title: "PW Studio 메인", views: 24, clicks: 0 },
      { path: "/portfolio", title: "제작 포트폴리오", views: 16, clicks: 0 },
      { path: "/contact", title: "프로젝트 문의하기", views: 9, clicks: 0 },
    ],
    actionItems: [
      "GA4 및 GSC 연동 완료에 따른 소상공인/전문직 웹사이트 제작 키워드 갭 분석 블로그 포스트 발행",
      "네이버 웹마스터 도구(서치어드바이저) 등록 및 사이트 구조 인덱싱 검증",
      "핵심 개발 실적 및 고객 사례 포트폴리오 섹션 고도화",
    ],
    targetMarket: "한국(ko-KR) 소상공인 & 비즈니스",
  },
  {
    id: "utahsays",
    name: "Utah Says",
    shortName: "Utah Says",
    domain: "utahsays.com",
    url: "https://utahsays.com",
    category: "유타 로컬 커뮤니티 & 리서치 미디어",
    badge: "로컬 미디어",
    icon: "🏔️",
    accentColor: "#10b981",
    stack: "Next.js · Cloudflare Workers / KV",
    integrations: {
      gsc: { connected: true, property: "sc-domain:utahsays.com", account: "garmgoondev@gmail.com" },
      ga4: { connected: true, property: "properties/557341522", stream: "Utah Says (G-QL3BW0J3KY)" },
      cloudflare: { connected: true, type: "Worker Custom Domain + KV" },
      audit: { status: "완료", issues: 14 },
    },
    overview: {
      clicks28d: 0,
      impressions28d: 42,
      ctr: 0.0,
      avgPosition: 28.6,
      users28d: 14,
      sessions28d: 19,
      engagementRate: 100,
      avgDuration: "3분 10초",
      indexedPages: 16,
      conversions: { label: "설문 투표 및 의견 등록", count: 12, unit: "건" },
      periods: {
        "7d": {
          clicks: 0,
          impressions: 15,
          ctr: 0.0,
          avgPosition: 27.2,
          users: 5,
          sessions: 7,
          engagementRate: 100,
          avgDuration: "3분 20초",
          conversions: 4,
        },
        "28d": {
          clicks: 0,
          impressions: 42,
          ctr: 0.0,
          avgPosition: 28.6,
          users: 14,
          sessions: 19,
          engagementRate: 100,
          avgDuration: "3분 10초",
          conversions: 12,
        },
        "90d": {
          clicks: 2,
          impressions: 118,
          ctr: 1.7,
          avgPosition: 29.8,
          users: 36,
          sessions: 52,
          engagementRate: 98,
          avgDuration: "2분 55초",
          conversions: 28,
        },
      },
    },
    history: {
      "7d": [
        { date: "10/02", impressions: 4, clicks: 0, users: 1 },
        { date: "10/03", impressions: 6, clicks: 0, users: 3 },
        { date: "10/04", impressions: 7, clicks: 0, users: 2 },
        { date: "10/05", impressions: 5, clicks: 0, users: 2 },
        { date: "10/06", impressions: 8, clicks: 0, users: 3 },
        { date: "10/07", impressions: 6, clicks: 0, users: 2 },
        { date: "10/08", impressions: 6, clicks: 0, users: 3 },
      ],
      "28d": [
        { date: "09/10", impressions: 4, clicks: 0, users: 1 },
        { date: "09/14", impressions: 5, clicks: 0, users: 2 },
        { date: "09/18", impressions: 6, clicks: 0, users: 2 },
        { date: "09/22", impressions: 7, clicks: 0, users: 2 },
        { date: "09/26", impressions: 6, clicks: 0, users: 2 },
        { date: "09/30", impressions: 8, clicks: 0, users: 3 },
        { date: "10/04", impressions: 7, clicks: 0, users: 2 },
        { date: "10/08", impressions: 6, clicks: 0, users: 3 },
      ],
      "90d": [
        { date: "07/15", impressions: 12, clicks: 0, users: 4 },
        { date: "07/30", impressions: 16, clicks: 1, users: 6 },
        { date: "08/15", impressions: 20, clicks: 0, users: 7 },
        { date: "08/30", impressions: 24, clicks: 1, users: 8 },
        { date: "09/15", impressions: 26, clicks: 0, users: 8 },
        { date: "09/30", impressions: 28, clicks: 0, users: 9 },
        { date: "10/08", impressions: 30, clicks: 0, users: 10 },
      ],
    },
    history7d: [
      { date: "10/02", impressions: 4, clicks: 0, users: 1 },
      { date: "10/03", impressions: 6, clicks: 0, users: 3 },
      { date: "10/04", impressions: 7, clicks: 0, users: 2 },
      { date: "10/05", impressions: 5, clicks: 0, users: 2 },
      { date: "10/06", impressions: 8, clicks: 0, users: 3 },
      { date: "10/07", impressions: 6, clicks: 0, users: 2 },
      { date: "10/08", impressions: 6, clicks: 0, users: 3 },
    ],
    topQueries: [
      { query: "utah local surveys community", rank: 24.1, clicks: 0, impressions: 14, ctr: 0.0, status: "상위 타깃" },
      { query: "utah public opinion polls", rank: 29.5, clicks: 0, impressions: 12, ctr: 0.0, status: "인덱싱 완료" },
      { query: "salt lake city community pulse", rank: 31.0, clicks: 0, impressions: 8, ctr: 0.0, status: "틈새 키워드" },
      { query: "utah says polls", rank: 12.0, clicks: 0, impressions: 5, ctr: 0.0, status: "브랜드 키워드" },
    ],
    topPages: [
      { path: "/", title: "Utah Says Home", views: 32, clicks: 0 },
      { path: "/polls/community-topics", title: "유타 주민 여론조사 토론", views: 21, clicks: 0 },
    ],
    actionItems: [
      "솔트레이크시티/유타 카운티 로컬 이슈 관련 주간 여론조사(Poll) 콘텐츠 지속 발행 및 사이트맵 자동 핑",
      "Reddit r/Utah 및 로컬 페이스북 커뮤니티 공유 연계로 초기 오가닉 유입 활성화",
      "사용자 응답 실시간 집계 위젯 UI 강화",
    ],
    targetMarket: "미국 유타주 로컬 (en-US)",
  },
  {
    id: "webomok",
    name: "WebOmok (웹오목)",
    shortName: "WebOmok",
    domain: "webomok.com",
    url: "https://webomok.com",
    category: "무설치 글로벌 2인용 온라인 오목 웹앱",
    badge: "글로벌 게임",
    icon: "⚪⚫",
    accentColor: "#6366f1",
    stack: "WebGame Network · Cloudflare Pages · PeerJS P2P",
    integrations: {
      gsc: { connected: true, property: "sc-domain:webomok.com", account: "garmgoondev@gmail.com" },
      ga4: { connected: true, property: "연동 완료", stream: "WebOmok Analytics" },
      cloudflare: { connected: true, type: "Pages + Edge Caching" },
      audit: { status: "완료", issues: 4 },
    },
    overview: {
      clicks28d: 8,
      impressions28d: 148,
      ctr: 5.4,
      avgPosition: 18.2,
      users28d: 64,
      sessions28d: 98,
      engagementRate: 96.0,
      avgDuration: "6분 45초",
      indexedPages: 12,
      conversions: { label: "총 대국 생성 및 플레이", count: 142, unit: "판" },
      periods: {
        "7d": {
          clicks: 3,
          impressions: 58,
          ctr: 5.2,
          avgPosition: 17.4,
          users: 24,
          sessions: 38,
          engagementRate: 97.0,
          avgDuration: "7분 10초",
          conversions: 52,
        },
        "28d": {
          clicks: 8,
          impressions: 148,
          ctr: 5.4,
          avgPosition: 18.2,
          users: 64,
          sessions: 98,
          engagementRate: 96.0,
          avgDuration: "6분 45초",
          conversions: 142,
        },
        "90d": {
          clicks: 22,
          impressions: 410,
          ctr: 5.4,
          avgPosition: 19.0,
          users: 175,
          sessions: 280,
          engagementRate: 95.5,
          avgDuration: "6분 30초",
          conversions: 390,
        },
      },
    },
    history: {
      "7d": [
        { date: "10/02", impressions: 16, clicks: 1, users: 8 },
        { date: "10/03", impressions: 20, clicks: 1, users: 9 },
        { date: "10/04", impressions: 24, clicks: 2, users: 12 },
        { date: "10/05", impressions: 21, clicks: 1, users: 10 },
        { date: "10/06", impressions: 28, clicks: 2, users: 14 },
        { date: "10/07", impressions: 22, clicks: 1, users: 11 },
        { date: "10/08", impressions: 25, clicks: 1, users: 12 },
      ],
      "28d": [
        { date: "09/10", impressions: 18, clicks: 1, users: 8 },
        { date: "09/14", impressions: 22, clicks: 1, users: 9 },
        { date: "09/18", impressions: 26, clicks: 1, users: 11 },
        { date: "09/22", impressions: 24, clicks: 1, users: 10 },
        { date: "09/26", impressions: 30, clicks: 2, users: 13 },
        { date: "09/30", impressions: 28, clicks: 1, users: 12 },
        { date: "10/04", impressions: 24, clicks: 2, users: 12 },
        { date: "10/08", impressions: 25, clicks: 1, users: 12 },
      ],
      "90d": [
        { date: "07/15", impressions: 45, clicks: 2, users: 18 },
        { date: "07/30", impressions: 55, clicks: 3, users: 24 },
        { date: "08/15", impressions: 68, clicks: 4, users: 31 },
        { date: "08/30", impressions: 72, clicks: 4, users: 34 },
        { date: "09/15", impressions: 84, clicks: 5, users: 40 },
        { date: "09/30", impressions: 92, clicks: 5, users: 44 },
        { date: "10/08", impressions: 98, clicks: 6, users: 48 },
      ],
    },
    history7d: [
      { date: "10/02", impressions: 16, clicks: 1, users: 8 },
      { date: "10/03", impressions: 20, clicks: 1, users: 9 },
      { date: "10/04", impressions: 24, clicks: 2, users: 12 },
      { date: "10/05", impressions: 21, clicks: 1, users: 10 },
      { date: "10/06", impressions: 28, clicks: 2, users: 14 },
      { date: "10/07", impressions: 22, clicks: 1, users: 11 },
      { date: "10/08", impressions: 25, clicks: 1, users: 12 },
    ],
    topQueries: [
      { query: "오목게임", rank: 14.8, clicks: 3, impressions: 45, ctr: 6.7, status: "🔥 최우선 공략 (네이버 월 7,710건)" },
      { query: "온라인 오목 무설치", rank: 16.2, clicks: 2, impressions: 38, ctr: 5.3, status: "1페이지 진입 유력" },
      { query: "play gomoku online free", rank: 22.1, clicks: 2, impressions: 42, ctr: 4.8, status: "글로벌 영문 유입" },
      { query: "2인용 오목", rank: 19.5, clicks: 1, impressions: 23, ctr: 4.3, status: "동시 플레이 수요" },
      { query: "五目並べ オン라인", rank: 28.0, clicks: 0, impressions: 16, ctr: 0.0, status: "일본 구글 틈새" },
    ],
    topPages: [
      { path: "/", title: "WebOmok - 무설치 온라인 2인용 오목", views: 180, clicks: 8 },
      { path: "/how-to-play", title: "오목 렌주룰 및 33 금수 규칙 가이드", views: 45, clicks: 0 },
    ],
    actionItems: [
      "네이버 월 7,710회 검색량에 경쟁도 '낮음'인 '오목게임' 키워드 온페이지 최적화(Title, H1, FAQ 마크업)",
      "일본 구글 2위가 야후 지혜주머니일 정도로 경쟁이 희박하므로, 일본어 타깃 메타 태그 및 hreflang 보강",
      "P2P 대전 링크 원클릭 클립보드 복사 및 카카오톡/라인/트위터 공유 미리보기 카드(OG Tag) 고도화",
    ],
    targetMarket: "한국, 일본, 대만, 미국 4개 국어 지원",
  },
  {
    id: "ecocarpet",
    name: "EcoCarpet Utah",
    shortName: "EcoCarpet",
    domain: "new.ecocarpetutah.com",
    targetDomain: "ecocarpetutah.com",
    url: "https://new.ecocarpetutah.com",
    category: "로컬 카펫 & 실내 클리닝 비즈니스",
    badge: "로컬 비즈니스",
    icon: "✨",
    accentColor: "#059669",
    stack: "Next.js · Tailwind CSS · Cloudflare Pages",
    integrations: {
      gsc: { connected: false, property: "전환 대기 (본 도메인 Cutover 시)", account: "garmgoondev@gmail.com" },
      ga4: { connected: false, property: "신규 배포 준비 중", stream: "EcoCarpet New Web" },
      cloudflare: { connected: true, type: "Pages Staging Domain" },
      audit: { status: "데모 오디트 완료", issues: 5 },
    },
    overview: {
      clicks28d: 0,
      impressions28d: 0,
      ctr: 0.0,
      avgPosition: 0.0,
      users28d: 32,
      sessions28d: 48,
      engagementRate: 92.0,
      avgDuration: "4분 20초",
      indexedPages: 14,
      conversions: { label: "견적 계산기 사용 및 문의", count: 12, unit: "건" },
      periods: {
        "7d": {
          clicks: 0,
          impressions: 0,
          ctr: 0.0,
          avgPosition: 0.0,
          users: 11,
          sessions: 16,
          engagementRate: 91.0,
          avgDuration: "4분 10초",
          conversions: 4,
        },
        "28d": {
          clicks: 0,
          impressions: 0,
          ctr: 0.0,
          avgPosition: 0.0,
          users: 32,
          sessions: 48,
          engagementRate: 92.0,
          avgDuration: "4분 20초",
          conversions: 12,
        },
        "90d": {
          clicks: 0,
          impressions: 0,
          ctr: 0.0,
          avgPosition: 0.0,
          users: 84,
          sessions: 125,
          engagementRate: 91.5,
          avgDuration: "4분 15초",
          conversions: 29,
        },
      },
    },
    history: {
      "7d": [
        { date: "10/02", impressions: 0, clicks: 0, users: 4 },
        { date: "10/03", impressions: 0, clicks: 0, users: 5 },
        { date: "10/04", impressions: 0, clicks: 0, users: 6 },
        { date: "10/05", impressions: 0, clicks: 0, users: 4 },
        { date: "10/06", impressions: 0, clicks: 0, users: 5 },
        { date: "10/07", impressions: 0, clicks: 0, users: 4 },
        { date: "10/08", impressions: 0, clicks: 0, users: 4 },
      ],
      "28d": [
        { date: "09/10", impressions: 0, clicks: 0, users: 4 },
        { date: "09/14", impressions: 0, clicks: 0, users: 5 },
        { date: "09/18", impressions: 0, clicks: 0, users: 6 },
        { date: "09/22", impressions: 0, clicks: 0, users: 4 },
        { date: "09/26", impressions: 0, clicks: 0, users: 5 },
        { date: "09/30", impressions: 0, clicks: 0, users: 4 },
        { date: "10/04", impressions: 0, clicks: 0, users: 5 },
        { date: "10/08", impressions: 0, clicks: 0, users: 4 },
      ],
      "90d": [
        { date: "07/15", impressions: 0, clicks: 0, users: 9 },
        { date: "07/30", impressions: 0, clicks: 0, users: 12 },
        { date: "08/15", impressions: 0, clicks: 0, users: 15 },
        { date: "08/30", impressions: 0, clicks: 0, users: 14 },
        { date: "09/15", impressions: 0, clicks: 0, users: 16 },
        { date: "09/30", impressions: 0, clicks: 0, users: 18 },
        { date: "10/08", impressions: 0, clicks: 0, users: 20 },
      ],
    },
    history7d: [
      { date: "10/02", impressions: 0, clicks: 0, users: 4 },
      { date: "10/03", impressions: 0, clicks: 0, users: 5 },
      { date: "10/04", impressions: 0, clicks: 0, users: 6 },
      { date: "10/05", impressions: 0, clicks: 0, users: 4 },
      { date: "10/06", impressions: 0, clicks: 0, users: 5 },
      { date: "10/07", impressions: 0, clicks: 0, users: 4 },
      { date: "10/08", impressions: 0, clicks: 0, users: 4 },
    ],
    topQueries: [
      { query: "carpet cleaning utah county", rank: "타깃", clicks: 0, impressions: 2400, ctr: 0.0, status: "지역 메인 (월 2,400회)" },
      { query: "eco friendly carpet cleaning orem", rank: "타깃", clicks: 0, impressions: 580, ctr: 0.0, status: "친환경 틈새 (월 580회)" },
      { query: "upholstery cleaning provo", rank: "타깃", clicks: 0, impressions: 720, ctr: 0.0, status: "소파/매트리스 확장" },
      { query: "commercial floor cleaner salt lake", rank: "타깃", clicks: 0, impressions: 890, ctr: 0.0, status: "B2B 상업 클리닝" },
    ],
    topPages: [
      { path: "/", title: "EcoCarpet Utah 친환경 카펫 클리닝 메인", views: 56, clicks: 0 },
      { path: "/pricing", title: "투명 정찰제 가격표 및 무료 견적기", views: 34, clicks: 0 },
      { path: "/service-areas/orem", title: "Orem/Provo 서비스 지역 안내", views: 22, clicks: 0 },
    ],
    actionItems: [
      "기존 워드프레스 사이트에서 신규 Cloudflare Pages 플랫폼으로 본 도메인(ecocarpetutah.com) 정식 DNS 전환(Cutover)",
      "전환 즉시 GSC 소유권 확인 및 구글 비즈니스 프로필(GBP) 링크 동기화",
      "로컬 비즈니스 Schema.org 및 리뷰 리치 스니펫 구조화 데이터 적용",
    ],
    targetMarket: "미국 유타주 (Utah County, Orem, Provo, Salt Lake)",
  },
  {
    id: "garmgoon",
    name: "Garmgoon.com",
    shortName: "Garmgoon",
    domain: "garmgoon.com",
    url: "https://garmgoon.com",
    category: "도메인 포털 & 자동화 인프라 허브",
    badge: "개인 허브",
    icon: "👑",
    accentColor: "#ff5a36",
    stack: "Next.js App Router · Cloudflare Worker · D1 · R2",
    integrations: {
      gsc: { connected: true, property: "sc-domain:garmgoon.com", account: "garmgoondev@gmail.com" },
      ga4: { connected: false, property: "Cloudflare Web Analytics", stream: "garmgoon.com" },
      cloudflare: { connected: true, type: "Worker Custom Domain + D1 + R2" },
      audit: { status: "완료", issues: 56 },
    },
    overview: {
      clicks28d: 1,
      impressions28d: 18,
      ctr: 5.6,
      avgPosition: 10.1,
      users28d: 45,
      sessions28d: 82,
      engagementRate: 91.0,
      avgDuration: "3분 20초",
      indexedPages: 56,
      conversions: { label: "자동화 실행 및 도구 사용", count: 1440, unit: "회" },
      periods: {
        "7d": {
          clicks: 1,
          impressions: 7,
          ctr: 14.3,
          avgPosition: 9.8,
          users: 16,
          sessions: 28,
          engagementRate: 92.0,
          avgDuration: "3분 40초",
          conversions: 480,
        },
        "28d": {
          clicks: 1,
          impressions: 18,
          ctr: 5.6,
          avgPosition: 10.1,
          users: 45,
          sessions: 82,
          engagementRate: 91.0,
          avgDuration: "3분 20초",
          conversions: 1440,
        },
        "90d": {
          clicks: 4,
          impressions: 52,
          ctr: 7.7,
          avgPosition: 10.4,
          users: 128,
          sessions: 235,
          engagementRate: 90.0,
          avgDuration: "3분 15초",
          conversions: 4320,
        },
      },
    },
    history: {
      "7d": [
        { date: "10/02", impressions: 2, clicks: 0, users: 6 },
        { date: "10/03", impressions: 3, clicks: 0, users: 7 },
        { date: "10/04", impressions: 2, clicks: 1, users: 8 },
        { date: "10/05", impressions: 4, clicks: 0, users: 6 },
        { date: "10/06", impressions: 3, clicks: 0, users: 7 },
        { date: "10/07", impressions: 2, clicks: 0, users: 6 },
        { date: "10/08", impressions: 2, clicks: 0, users: 5 },
      ],
      "28d": [
        { date: "09/10", impressions: 2, clicks: 0, users: 5 },
        { date: "09/14", impressions: 3, clicks: 0, users: 6 },
        { date: "09/18", impressions: 2, clicks: 0, users: 5 },
        { date: "09/22", impressions: 4, clicks: 0, users: 7 },
        { date: "09/26", impressions: 3, clicks: 0, users: 6 },
        { date: "09/30", impressions: 2, clicks: 0, users: 6 },
        { date: "10/04", impressions: 2, clicks: 1, users: 8 },
        { date: "10/08", impressions: 2, clicks: 0, users: 5 },
      ],
      "90d": [
        { date: "07/15", impressions: 5, clicks: 0, users: 14 },
        { date: "07/30", impressions: 7, clicks: 1, users: 18 },
        { date: "08/15", impressions: 9, clicks: 1, users: 22 },
        { date: "08/30", impressions: 10, clicks: 0, users: 20 },
        { date: "09/15", impressions: 12, clicks: 1, users: 25 },
        { date: "09/30", impressions: 14, clicks: 1, users: 26 },
        { date: "10/08", impressions: 16, clicks: 0, users: 28 },
      ],
    },
    history7d: [
      { date: "10/02", impressions: 2, clicks: 0, users: 6 },
      { date: "10/03", impressions: 3, clicks: 0, users: 7 },
      { date: "10/04", impressions: 2, clicks: 1, users: 8 },
      { date: "10/05", impressions: 4, clicks: 0, users: 6 },
      { date: "10/06", impressions: 3, clicks: 0, users: 7 },
      { date: "10/07", impressions: 2, clicks: 0, users: 6 },
      { date: "10/08", impressions: 2, clicks: 0, users: 5 },
    ],
    topQueries: [
      { query: "garmgoon", rank: 1.0, clicks: 1, impressions: 5, ctr: 20.0, status: "1위 고정" },
      { query: "garmgoon dev", rank: 1.0, clicks: 0, impressions: 4, ctr: 0.0, status: "1위 고정" },
      { query: "자동화 대시보드 포트폴리오", rank: 14.2, clicks: 0, impressions: 8, ctr: 0.0, status: "2페이지 유입" },
    ],
    topPages: [
      { path: "/", title: "오늘의 카드", views: 210, clicks: 1 },
      { path: "/automations", title: "자동화 통합 현황판", views: 140, clicks: 0 },
      { path: "/tools", title: "SaaS 도구함", views: 60, clicks: 0 },
    ],
    actionItems: [
      "RSS 수집 파이프라인 자동화 10분 주기 모니터링 및 하트비트 정상 유지",
      "참조 도메인 451개 및 백링크 454개의 높은 도메인 권위도를 활용한 하위 프로젝트 연결 링크 강화",
      "개인 포트폴리오 프로젝트 소개 페이지 추가 및 구조화 데이터 보강",
    ],
    targetMarket: "글로벌 개발자 & 개인 네트워크",
  },
  {
    id: "seohub",
    name: "OpenSEO Hub",
    shortName: "SEO Hub",
    domain: "seo.garmgoon.com",
    url: "https://seo.garmgoon.com",
    category: "중앙 SEO 관제 및 MCP API 인프라",
    badge: "SEO 관제소",
    icon: "🌐",
    accentColor: "#0284c7",
    stack: "OpenSEO Self-hosted · Cloudflare Access · D1 · DataForSEO",
    integrations: {
      gsc: { connected: true, property: "중앙 OAuth 게이트웨이", account: "garmgoondev@gmail.com" },
      ga4: { connected: true, property: "중앙 GA4 커넥터", stream: "5개 속성 통합" },
      cloudflare: { connected: true, type: "Cloudflare Access Managed OAuth" },
      audit: { status: "완료", issues: 0 },
    },
    overview: {
      clicks28d: 0,
      impressions28d: 0,
      ctr: 0.0,
      avgPosition: 0.0,
      users28d: 6,
      sessions28d: 36,
      engagementRate: 100,
      avgDuration: "8분 15초",
      indexedPages: 1,
      conversions: { label: "SEO 오디트 & 주간 보고서 발행", count: 24, unit: "건" },
      periods: {
        "7d": {
          clicks: 0,
          impressions: 0,
          ctr: 0.0,
          avgPosition: 0.0,
          users: 2,
          sessions: 12,
          engagementRate: 100,
          avgDuration: "8분 30초",
          conversions: 8,
        },
        "28d": {
          clicks: 0,
          impressions: 0,
          ctr: 0.0,
          avgPosition: 0.0,
          users: 6,
          sessions: 36,
          engagementRate: 100,
          avgDuration: "8분 15초",
          conversions: 24,
        },
        "90d": {
          clicks: 0,
          impressions: 0,
          ctr: 0.0,
          avgPosition: 0.0,
          users: 16,
          sessions: 95,
          engagementRate: 100,
          avgDuration: "8분 00초",
          conversions: 72,
        },
      },
    },
    history: {
      "7d": [
        { date: "10/02", impressions: 0, clicks: 0, users: 1 },
        { date: "10/03", impressions: 0, clicks: 0, users: 1 },
        { date: "10/04", impressions: 0, clicks: 0, users: 2 },
        { date: "10/05", impressions: 0, clicks: 0, users: 3 },
        { date: "10/06", impressions: 0, clicks: 0, users: 2 },
        { date: "10/07", impressions: 0, clicks: 0, users: 1 },
        { date: "10/08", impressions: 0, clicks: 0, users: 2 },
      ],
      "28d": [
        { date: "09/10", impressions: 0, clicks: 0, users: 1 },
        { date: "09/14", impressions: 0, clicks: 0, users: 2 },
        { date: "09/18", impressions: 0, clicks: 0, users: 1 },
        { date: "09/22", impressions: 0, clicks: 0, users: 2 },
        { date: "09/26", impressions: 0, clicks: 0, users: 2 },
        { date: "09/30", impressions: 0, clicks: 0, users: 3 },
        { date: "10/04", impressions: 0, clicks: 0, users: 2 },
        { date: "10/08", impressions: 0, clicks: 0, users: 2 },
      ],
      "90d": [
        { date: "07/15", impressions: 0, clicks: 0, users: 2 },
        { date: "07/30", impressions: 0, clicks: 0, users: 3 },
        { date: "08/15", impressions: 0, clicks: 0, users: 4 },
        { date: "08/30", impressions: 0, clicks: 0, users: 4 },
        { date: "09/15", impressions: 0, clicks: 0, users: 5 },
        { date: "09/30", impressions: 0, clicks: 0, users: 5 },
        { date: "10/08", impressions: 0, clicks: 0, users: 6 },
      ],
    },
    history7d: [
      { date: "10/02", impressions: 0, clicks: 0, users: 1 },
      { date: "10/03", impressions: 0, clicks: 0, users: 1 },
      { date: "10/04", impressions: 0, clicks: 0, users: 2 },
      { date: "10/05", impressions: 0, clicks: 0, users: 3 },
      { date: "10/06", impressions: 0, clicks: 0, users: 2 },
      { date: "10/07", impressions: 0, clicks: 0, users: 1 },
      { date: "10/08", impressions: 0, clicks: 0, users: 2 },
    ],
    topQueries: [
      { query: "비공개 인트라넷", rank: 0, clicks: 0, impressions: 0, ctr: 0.0, status: "Cloudflare Access 보호" },
    ],
    topPages: [
      { path: "/", title: "OpenSEO 관리 대시보드", views: 88, clicks: 0 },
      { path: "/mcp", title: "OpenSEO MCP 엔드포인트", views: 120, clicks: 0 },
    ],
    actionItems: [
      "Cloudflare Access Managed OAuth 168시간 세션 만료 주기 모니터링",
      "DataForSEO 크레딧 잔여량 점검 및 주간 자동화 실행 결과 텔레그램 연동 유지",
    ],
    targetMarket: "운영자 전용 중앙 관제소",
  },
];

/**
 * 특정 기간(7d, 28d, 90d)에 맞는 사이트 집계 지표를 계산한다.
 */
export function getAggregatedStats(sites = SITES_METRICS, period = "28d") {
  let totalImpressions = 0;
  let totalClicks = 0;
  let totalUsers = 0;
  let totalConversions = 0;
  let activeSites = 0;

  for (const site of sites) {
    const pData = site.overview?.periods?.[period] || {
      clicks: site.overview?.clicks28d ?? 0,
      impressions: site.overview?.impressions28d ?? 0,
      users: site.overview?.users28d ?? 0,
      conversions: site.overview?.conversions?.count ?? 0,
    };

    if (typeof pData.impressions === "number") totalImpressions += pData.impressions;
    if (typeof pData.clicks === "number") totalClicks += pData.clicks;
    if (typeof pData.users === "number") totalUsers += pData.users;
    if (typeof pData.conversions === "number") totalConversions += pData.conversions;
    activeSites++;
  }

  const avgCtr = totalImpressions > 0 ? Math.round((totalClicks / totalImpressions) * 1000) / 10 : 0;

  return {
    period,
    totalSites: sites.length,
    activeSites,
    totalImpressions,
    totalClicks,
    avgCtr,
    totalUsers,
    totalConversions,
    // 호환성 유지용 28d 필드
    totalImpressions28d: totalImpressions,
    totalClicks28d: totalClicks,
    totalUsers28d: totalUsers,
  };
}

/**
 * 모든 지원 기간(7d, 28d, 90d)의 요약 데이터를 한 번에 가져온다.
 */
export function getAllPeriodTotals(sites = SITES_METRICS) {
  return {
    "7d": getAggregatedStats(sites, "7d"),
    "28d": getAggregatedStats(sites, "28d"),
    "90d": getAggregatedStats(sites, "90d"),
  };
}
